version: "3.8"

services:
  back:
    build:
      context: ./back
      dockerfile: Dockerfile
    image: back:fs1
    container_name: back_fs1
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=production
      - PORT=5000

  front:
    build:
      context: ./front
      dockerfile: Dockerfile
    image: front:fs1
    container_name: front_fs1
    ports:
      - "80:80"
      - "443:443" # Add HTTPS port
    volumes:
      - certbot-data:/etc/letsencrypt
    environment:
      - NODE_ENV=production
      - DOMAIN=${DOMAIN} # Use environment variable
    restart: unless-stopped

  certbot:
    image: certbot/certbot:latest
    volumes:
      - certbot-data:/etc/letsencrypt
      - certbot-webroot:/var/www/certbot
    depends_on:
      - front
    command: certonly --webroot --webroot-path=/var/www/certbot --email ${EMAIL} --agree-tos --no-eff-email -d ${DOMAIN}

volumes:
  certbot-data:
  certbot-webroot:
