version: "3.8"

services:
  back:
    build:
      context: ./back
      dockerfile: Dockerfile
    image: back:fs1
    container_name: back_fs1
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=production
      - PORT=5000
      - MONGO_URI=${MONGO_URI}

  front:
    build:
      context: ./front
      dockerfile: Dockerfile
    image: front:fs1
    container_name: front_fs1
    ports:
      - "80:80"
    environment:
      - NODE_ENV=production
