name: Auto Merge Pull Requests

on:
  pull_request:
    types:
      - opened
      - reopened

jobs:
  auto-merge:
    runs-on: fs1
    steps:
      - uses: alexwilson/enable-github-automerge-action@2.0.0
        with:
          github-token: "${{ secrets.GITHUB_TOKEN }}"
