name: Auto Merge Pull Requests

on:
  pull_request_review:
    types:
      - submitted
  check_suite:
    types:
      - completed
  status: {}

jobs:
  auto-merge:
    runs-on: ubuntu-latest
    steps:
      - name: Auto Merge
        uses: pascalgn/automerge-action@v0.15.6
        env:
          GITHUB_TOKEN: ${{ secrets.FS1_MERN_GH_TOKEN }}
          MERGE_LABELS: "automerge,!work in progress"
          MERGE_METHOD: "squash"
          MERGE_COMMIT_MESSAGE: "pull-request-title"
          MERGE_FORKS: "false"
          MERGE_RETRIES: "6"
          MERGE_RETRY_SLEEP: "10000"
          MERGE_REQUIRED_APPROVALS: "1"
          UPDATE_LABELS: "automerge"
          UPDATE_METHOD: "rebase"

    build-front:
      runs-on: fs1
      needs: auto-merge
      steps:
        - name: Checkout code
          uses: actions/checkout@v2

        - name: Build Frontend
          run: |
            cd front
            docker build -t react-app-local .
            docker tag react-app-local:latest react-app-local:${{ github.sha }}
    
    deploy-front:
      runs-on: fs1
      needs: auto-merge
      steps:
        - name: Checkout code
          uses: actions/checkout@v2

        - name: Deploy Frontend
          run: |
            cd front
            helm upgrade --install react-app ./helmchart --set image.tag=${{ github.sha }}
