name: Auto Merge Pull Requests

on:
  pull_request:
    types:
      - opened
      - reopened

jobs:
  auto-merge:
    runs-on: fs1
    env:
      REPO_GITHUB_TOKEN: ${{ secrets.FS1_MERN_GH_TOKEN }}
    steps:
      - uses: alexwilson/enable-github-automerge-action@2.0.0
        with:
          github-token: "${{ env.REPO_GITHUB_TOKEN }}"
