name: Build and Deploy Docker Compose

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: fs1
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Replace secrets
        run: |
          sed -i "s|\${EMAIL}|${{ secrets.EMAIL }}|g" docker-compose.yml
          sed -i "s|\${DOMAIN}|${{ secrets.DOMAIN }}|g" docker-compose.yml
          sed -i "s|\${DOMAIN}|${{ secrets.DOMAIN }}|g" front/nginx.conf

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker images
        run: |
          docker-compose build

      - name: Deploy containers
        run: |
          docker-compose up -d
